# Generated by Django 4.1.13 on 2024-02-28 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hospital_admin", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hospitalhome", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialization",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hospitalhome.hospital_information",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hospitalhome.hospital_information",
            ),
        ),
        migrations.AddField(
            model_name="hospital_department",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hospitalhome.hospital_information",
            ),
        ),
        migrations.AddField(
            model_name="clinical_laboratory_technician",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hospitalhome.hospital_information",
            ),
        ),
        migrations.AddField(
            model_name="clinical_laboratory_technician",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="technician",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="admin_information",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hospitalhome.hospital_information",
            ),
        ),
        migrations.AddField(
            model_name="admin_information",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hospital_admin",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
